export interface ICreateOrUpdate {
    name: string;
    card_number: number | null;
    gender: number;
    mother_name: string | null;
    dob: string;
    pob: string ;
    ktp_no: number;
    nc_id: number;
    home_address_1: string | null;
    home_address_2: string | null;
    mobile_no: number | null;
    tel_no: number | null;
    marriage_id: number | null;
    bank_account_no: number | null;
    bank_name: string | null;
    family_card_number: number | null;
    safety_insurance_no: number | null;
    health_insurance_no: number | null;
    department_id:number;
    position_id: number | null;
    shift: string;
    type: string;
    entitle_ot: string;
    meal_allowance_paid: string;
    operational_allowance_paid: string;
    attendance_allowance_paid: string;
    basic_salary: number;
    audit_salary: number;
    safety_insurance: number;
    health_insurance: number;
    meal_allowance: number;
    contract_start_date: string;
    grade_id: number | null;
    remark: string | null;
    benefits: number[];
    account_user_id: number;
}

export interface ICreateOrUpdateValidation {
    name: string;
    card_number: number | null;
    gender: number;
    mother_name: string | null;
    dob: string;
    pob: string ;
    ktp_no: number;
    nc_id: number;
    home_address_1: string | null;
    home_address_2: string | null;
    mobile_no: number | null;
    tel_no: number | null;
    marriage_id: number | null;
    bank_account_no: number | null;
    bank_name: string | null;
    family_card_number: number | null;
    safety_insurance_no: number | null;
    health_insurance_no: number | null;
    department_id:number;
    position_id: number | null;
    shift: string;
    type: string;
    entitle_ot: string;
    meal_allowance_paid: string;
    operational_allowance_paid: string;
    attendance_allowance_paid: string;
    basic_salary: number;
    audit_salary: number;
    safety_insurance: number;
    health_insurance: number;
    meal_allowance: number;
    contract_start_date: string;
    grade_id: number | null;
    remark: string | null;
    benefits: number[];
    account_user_id: number;
}
